#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=01

name=tailscaled
pid_file="/var/run/$name.pid"
tsd_init="/etc/init.d/$name"
state="/etc/tailscale/$name.state"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

[ -e /etc/sysconfig/$name ] && . /etc/sysconfig/$name

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps $(get_pid) > /dev/null 2>&1
}

boot() {
    ubus -t 30 wait_for network.interface network.loopback 2>/dev/null
    rc_procd start_service
}

start_service() {
    if [ $("${tsd_init}" enabled; printf "%u" ${?}) -eq 0 ]
    then
        /usr/sbin/${name} --cleanup

        if is_running; then
            echo "Already started"
        else
            echo "Starting $name"

            procd_open_instance
            procd_set_param command /usr/sbin/${name} --state=${state} --port=41641 >> ${stdout_log} 2>> ${stderr_log}

            procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

            procd_set_param term_timeout 60
            procd_close_instance
        fi
    fi
}

stop_service() {
    /usr/sbin/${name} --cleanup
    if is_running; then
        echo -n "Stopping $name.."
        kill $(get_pid)
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi
            echo -n "."
            sleep 1
        done
        echo
        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
}
